import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

// サポートする言語の定義
export type Language = 'ja' | 'en' | 'id' | 'zh';

export interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  getCurrentLanguageName: () => string;
  getAvailableLanguages: () => Array<{ code: Language; name: string; nativeName: string }>;
}

// 言語名の定義
const languages = {
  ja: { name: 'Japanese', nativeName: '日本語' },
  en: { name: 'English', nativeName: 'English' },
  id: { name: 'Indonesian', nativeName: 'Bahasa Indonesia' },
  zh: { name: 'Chinese', nativeName: '中文' },
};

// 翻訳データ
const translations: Record<Language, Record<string, string>> = {
  ja: {
    // 共通
    'common.save': '保存',
    'common.cancel': 'キャンセル',
    'common.reset': 'リセット',
    'common.close': '閉じる',
    'common.confirm': '確認',
    'common.delete': '削除',
    'common.edit': '編集',
    'common.add': '追加',
    'common.search': '検索',
    'common.loading': '読み込み中...',
    'common.error': 'エラー',
    'common.success': '成功',
    
    // サイドバー
    'sidebar.projects': 'プロジェクト',
    'sidebar.simulator': 'シミュレーター',
    'sidebar.networkEditor': 'ネットワーク編集',
    'sidebar.componentEditor': '部品編集',
    'sidebar.analytics': '分析',
    'sidebar.help': 'ヘルプ',
    'sidebar.settings': '設定',
    'sidebar.sidebarConfig': 'サイドバー設定',
    
    // 設定パネル
    'settings.title': '設定',
    'settings.appearance': '外観',
    'settings.language': '言語・地域',
    'settings.notifications': '通知',
    'settings.dataStorage': 'データ・ストレージ',
    'settings.security': 'セキュリティ',
    'settings.theme': 'テーマ',
    'settings.theme.light': 'ライト',
    'settings.theme.dark': 'ダーク',
    'settings.theme.auto': '自動',
    'settings.autoSave': '自動保存を有効にする',
    'settings.language.label': '言語',
    'settings.notifications.enable': '通知を有効にする',
    'settings.simulationSpeed': 'シミュレーション速度',
    'settings.maxIterations': '最大イテレーション数',
    'settings.dataRetention': 'データ保持期間（日）',
    'settings.securityLevel': 'セキュリティレベル',
    'settings.securityLevel.low': '低',
    'settings.securityLevel.medium': '中',
    'settings.securityLevel.high': '高',
    'settings.securityLevel.info': 'セキュリティレベルを変更すると、次回のログインから適用されます。',
    
    // サイドバー設定
    'sidebarConfig.title': 'サイドバー設定',
    'sidebarConfig.appearance': '外観',
    'sidebarConfig.behavior': '動作',
    'sidebarConfig.shortcuts': 'ショートカット',
    'sidebarConfig.showSidebar': 'サイドバーを表示',
    'sidebarConfig.sidebarWidth': 'サイドバー幅',
    'sidebarConfig.currentWidth': '現在: {width}px',
    'sidebarConfig.hoverHighlight': 'ホバー時にハイライト',
    'sidebarConfig.activeItemHighlight': 'アクティブ項目を強調',
    'sidebarConfig.animationEffects': 'アニメーション効果',
    'sidebarConfig.keyboardShortcuts': 'キーボードショートカット',
    'sidebarConfig.quickActions': 'クイックアクション',
    'sidebarConfig.resetSettings': '設定をリセット',
    'sidebarConfig.exportSettings': '設定をエクスポート',
    'sidebarConfig.importSettings': '設定をインポート',
    
    // キーボードショートカット
    'shortcuts.sidebarToggle': 'Ctrl + B: サイドバー表示/非表示',
    'shortcuts.settingsPanel': 'Ctrl + Shift + S: 設定パネル',
    'shortcuts.sidebarConfig': 'Ctrl + Shift + C: サイドバー設定',
    'shortcuts.newProject': 'Ctrl + Shift + N: 新規プロジェクト',
    
         // アプリケーション
     'app.title': '混流生産ライン離散シミュレーター',
     'app.productionSimulator': '生産シミュレーター',
     
     // ネットワーク編集
     'network.title': 'ネットワーク編集',
     'network.addProcess': 'プロセス追加',
     'network.addStore': 'ストア追加',
     'network.addConnection': '接続追加',
     'network.editProcess': 'プロセス編集',
     'network.editStore': 'ストア編集',
     'network.editConnection': '接続編集',
     'network.deleteProcess': 'プロセス削除',
     'network.deleteStore': 'ストア削除',
     'network.deleteConnection': '接続削除',
     'network.processName': 'プロセス名',
     'network.storeName': 'ストア名',
     'network.connectionName': '接続名',
     'network.processType': 'プロセスタイプ',
     'network.storeType': 'ストアタイプ',
     'network.connectionType': '接続タイプ',
     'network.capacity': '容量',
     'network.initialStock': '初期在庫',
     'network.processingTime': '処理時間',
     'network.transportTime': '輸送時間',
     'network.distance': '距離',
     'network.coordinates': '座標',
     'network.x': 'X座標',
     'network.y': 'Y座標',
     'network.validation': '検証',
     'network.validationSuccess': '検証成功',
     'network.validationError': '検証エラー',
     'network.validationWarning': '検証警告',
     'network.saveNetwork': 'ネットワーク保存',
     'network.loadNetwork': 'ネットワーク読み込み',
     'network.exportNetwork': 'ネットワークエクスポート',
     'network.importNetwork': 'ネットワークインポート',
     'network.clearNetwork': 'ネットワーククリア',
     'network.undo': '元に戻す',
     'network.redo': 'やり直し',
     'network.zoomIn': '拡大',
     'network.zoomOut': '縮小',
     'network.fitToScreen': '画面に合わせる',
     'network.resetView': 'ビューリセット',
     'network.grid': 'グリッド',
     'network.snapToGrid': 'グリッドにスナップ',
     'network.showLabels': 'ラベル表示',
     'network.showConnections': '接続表示',
     'network.showProcesses': 'プロセス表示',
     'network.showStores': 'ストア表示',
     'network.autoLayout': '自動レイアウト',
     'network.manualLayout': '手動レイアウト',
     'network.analysis': '分析',
     'network.bottleneckAnalysis': 'ボトルネック分析',
     'network.flowAnalysis': 'フロー分析',
     'network.efficiencyAnalysis': '効率性分析',
     'network.costAnalysis': 'コスト分析',
     'network.performanceMetrics': '性能指標',
     'network.throughput': 'スループット',
     'network.utilization': '稼働率',
     'network.cycleTime': 'サイクルタイム',
     'network.leadTime': 'リードタイム',
     'network.workInProgress': '仕掛品',
     'network.finishedGoods': '完成品',
     'network.rawMaterials': '原材料',
     'network.workInProgressStore': '仕掛品ストア',
     'network.finishedGoodsStore': '完成品ストア',
     'network.rawMaterialsStore': '原材料ストア',
     'network.machine': '機械',
     'network.worker': '作業者',
     'network.transport': '輸送',
     'network.buffer': 'バッファ',
     'network.quality': '品質',
     'network.maintenance': 'メンテナンス',
     'network.setup': 'セットアップ',
     'network.breakdown': '故障',
     'network.repair': '修理',
     'network.schedule': 'スケジュール',
     'network.shift': 'シフト',
     'network.overtime': '残業',
     'network.break': '休憩',
     'network.availability': '稼働可能時間',
     'network.efficiency': '効率',
     'network.reliability': '信頼性',
     'network.flexibility': '柔軟性',
     'network.scalability': 'スケーラビリティ',
     'network.optimization': '最適化',
     'network.simulation': 'シミュレーション',
     'network.parameters': 'パラメータ',
     'network.results': '結果',
     'network.reports': 'レポート',
     'network.charts': 'チャート',
     'network.graphs': 'グラフ',
     'network.tables': 'テーブル',
     'network.exportData': 'データエクスポート',
     'network.print': '印刷',
     'network.help': 'ヘルプ',
     'network.tutorial': 'チュートリアル',
     'network.shortcuts': 'ショートカット',
     'network.about': 'について',
     
     // 工程パラメーター
     'process.cycleTime': 'サイクルタイム',
     'process.setupTime': 'セットアップ時間',
     'process.equipmentCount': '設備台数',
     'process.operatorCount': '作業者数',
     'process.inputBufferCapacity': '入力バッファ容量',
     'process.outputBufferCapacity': '出力バッファ容量',
     'process.defectRate': '不良率',
     'process.reworkRate': '手直し率',
     'process.operatingCost': '運転コスト',
     'process.machining': '機械加工',
     'process.assembly': '組立',
     'process.inspection': '検査',
     'process.packaging': '包装',
     'process.storage': '保管',
     'process.transport': '輸送',
     'process.basicSettings': '基本設定',
     'process.advancedSettings': '詳細設定',
     'process.materialSettings': '材料設定',
     'process.outputSettings': '出力設定',
     'process.qualitySettings': '品質設定',
     'process.costSettings': 'コスト設定',
     'process.scheduleSettings': 'スケジュール設定',
     'process.unit.seconds': '秒',
     'process.unit.minutes': '分',
     'process.unit.hours': '時間',
     'process.unit.pieces': '個',
     'process.unit.percent': '%',
     'process.unit.yen': '円',
     
     // ストア設定
     'store.title': 'ストア設定',
     'store.finishedProductStore': '完成品ストア',
     'store.componentStore': '部品ストア',
     'store.storeType': 'ストアタイプ',
     'store.inputBufferCapacity': '入力バッファ容量',
     'store.outputBufferCapacity': '出力バッファ容量',
     'store.productionSchedule': '生産計画',
     'store.inventoryLevels': '在庫レベル',
     'store.addSchedule': '計画追加',
     'store.addInventory': '在庫追加',
     'store.sequence': '順序',
     'store.productName': '製品名',
     'store.quantity': '数量',
     'store.unit': '単位',
     'store.priority': '優先度',
     'store.startTime': '開始時刻',
     'store.endTime': '終了時刻',
     'store.status': '状態',
     'store.actions': '操作',
     'store.active': '有効',
     'store.inactive': '無効',
     'store.currentStock': '現在在庫',
     'store.minStock': '最小在庫',
     'store.maxStock': '最大在庫',
     'store.reorderPoint': '発注点',
     'store.addScheduleTitle': '生産計画追加',
     'store.editScheduleTitle': '生産計画編集',
     'store.addInventoryTitle': '在庫レベル追加',
     'store.editInventoryTitle': '在庫レベル編集',
     'store.productId': '製品ID',
     'store.unit.pieces': '個',
     'store.unit.hours': '時間',
   },
  
  en: {
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.reset': 'Reset',
    'common.close': 'Close',
    'common.confirm': 'Confirm',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    
    // Sidebar
    'sidebar.projects': 'Projects',
    'sidebar.simulator': 'Simulator',
    'sidebar.networkEditor': 'Network Editor',
    'sidebar.componentEditor': 'Component Editor',
    'sidebar.analytics': 'Analytics',
    'sidebar.help': 'Help',
    'sidebar.settings': 'Settings',
    'sidebar.sidebarConfig': 'Sidebar Config',
    
    // Settings Panel
    'settings.title': 'Settings',
    'settings.appearance': 'Appearance',
    'settings.language': 'Language & Region',
    'settings.notifications': 'Notifications',
    'settings.dataStorage': 'Data & Storage',
    'settings.security': 'Security',
    'settings.theme': 'Theme',
    'settings.theme.light': 'Light',
    'settings.theme.dark': 'Dark',
    'settings.theme.auto': 'Auto',
    'settings.autoSave': 'Enable Auto Save',
    'settings.language.label': 'Language',
    'settings.notifications.enable': 'Enable Notifications',
    'settings.simulationSpeed': 'Simulation Speed',
    'settings.maxIterations': 'Max Iterations',
    'settings.dataRetention': 'Data Retention (days)',
    'settings.securityLevel': 'Security Level',
    'settings.securityLevel.low': 'Low',
    'settings.securityLevel.medium': 'Medium',
    'settings.securityLevel.high': 'High',
    'settings.securityLevel.info': 'Security level changes will take effect on next login.',
    
    // Sidebar Config
    'sidebarConfig.title': 'Sidebar Configuration',
    'sidebarConfig.appearance': 'Appearance',
    'sidebarConfig.behavior': 'Behavior',
    'sidebarConfig.shortcuts': 'Shortcuts',
    'sidebarConfig.showSidebar': 'Show Sidebar',
    'sidebarConfig.sidebarWidth': 'Sidebar Width',
    'sidebarConfig.currentWidth': 'Current: {width}px',
    'sidebarConfig.hoverHighlight': 'Highlight on Hover',
    'sidebarConfig.activeItemHighlight': 'Highlight Active Item',
    'sidebarConfig.animationEffects': 'Animation Effects',
    'sidebarConfig.keyboardShortcuts': 'Keyboard Shortcuts',
    'sidebarConfig.quickActions': 'Quick Actions',
    'sidebarConfig.resetSettings': 'Reset Settings',
    'sidebarConfig.exportSettings': 'Export Settings',
    'sidebarConfig.importSettings': 'Import Settings',
    
    // Keyboard Shortcuts
    'shortcuts.sidebarToggle': 'Ctrl + B: Toggle Sidebar',
    'shortcuts.settingsPanel': 'Ctrl + Shift + S: Settings Panel',
    'shortcuts.sidebarConfig': 'Ctrl + Shift + C: Sidebar Config',
    'shortcuts.newProject': 'Ctrl + Shift + N: New Project',
    
         // Application
     'app.title': 'Mixed Production Line Discrete Simulator',
     'app.productionSimulator': 'Production Simulator',
     
     // Network Editor
     'network.title': 'Network Editor',
     'network.addProcess': 'Add Process',
     'network.addStore': 'Add Store',
     'network.addConnection': 'Add Connection',
     'network.editProcess': 'Edit Process',
     'network.editStore': 'Edit Store',
     'network.editConnection': 'Edit Connection',
     'network.deleteProcess': 'Delete Process',
     'network.deleteStore': 'Delete Store',
     'network.deleteConnection': 'Delete Connection',
     'network.processName': 'Process Name',
     'network.storeName': 'Store Name',
     'network.connectionName': 'Connection Name',
     'network.processType': 'Process Type',
     'network.storeType': 'Store Type',
     'network.connectionType': 'Connection Type',
     'network.capacity': 'Capacity',
     'network.initialStock': 'Initial Stock',
     'network.processingTime': 'Processing Time',
     'network.transportTime': 'Transport Time',
     'network.distance': 'Distance',
     'network.coordinates': 'Coordinates',
     'network.x': 'X Coordinate',
     'network.y': 'Y Coordinate',
     'network.validation': 'Validation',
     'network.validationSuccess': 'Validation Success',
     'network.validationError': 'Validation Error',
     'network.validationWarning': 'Validation Warning',
     'network.saveNetwork': 'Save Network',
     'network.loadNetwork': 'Load Network',
     'network.exportNetwork': 'Export Network',
     'network.importNetwork': 'Import Network',
     'network.clearNetwork': 'Clear Network',
     'network.undo': 'Undo',
     'network.redo': 'Redo',
     'network.zoomIn': 'Zoom In',
     'network.zoomOut': 'Zoom Out',
     'network.fitToScreen': 'Fit to Screen',
     'network.resetView': 'Reset View',
     'network.grid': 'Grid',
     'network.snapToGrid': 'Snap to Grid',
     'network.showLabels': 'Show Labels',
     'network.showConnections': 'Show Connections',
     'network.showProcesses': 'Show Processes',
     'network.showStores': 'Show Stores',
     'network.autoLayout': 'Auto Layout',
     'network.manualLayout': 'Manual Layout',
     'network.analysis': 'Analysis',
     'network.bottleneckAnalysis': 'Bottleneck Analysis',
     'network.flowAnalysis': 'Flow Analysis',
     'network.efficiencyAnalysis': 'Efficiency Analysis',
     'network.costAnalysis': 'Cost Analysis',
     'network.performanceMetrics': 'Performance Metrics',
     'network.throughput': 'Throughput',
     'network.utilization': 'Utilization',
     'network.cycleTime': 'Cycle Time',
     'network.leadTime': 'Lead Time',
     'network.workInProgress': 'Work in Progress',
     'network.finishedGoods': 'Finished Goods',
     'network.rawMaterials': 'Raw Materials',
     'network.workInProgressStore': 'WIP Store',
     'network.finishedGoodsStore': 'Finished Goods Store',
     'network.rawMaterialsStore': 'Raw Materials Store',
     'network.machine': 'Machine',
     'network.worker': 'Worker',
     'network.transport': 'Transport',
     'network.buffer': 'Buffer',
     'network.quality': 'Quality',
     'network.maintenance': 'Maintenance',
     'network.setup': 'Setup',
     'network.breakdown': 'Breakdown',
     'network.repair': 'Repair',
     'network.schedule': 'Schedule',
     'network.shift': 'Shift',
     'network.overtime': 'Overtime',
     'network.break': 'Break',
     'network.availability': 'Availability',
     'network.efficiency': 'Efficiency',
     'network.reliability': 'Reliability',
     'network.flexibility': 'Flexibility',
     'network.scalability': 'Scalability',
     'network.optimization': 'Optimization',
     'network.simulation': 'Simulation',
     'network.parameters': 'Parameters',
     'network.results': 'Results',
     'network.reports': 'Reports',
     'network.charts': 'Charts',
     'network.graphs': 'Graphs',
     'network.tables': 'Tables',
     'network.exportData': 'Export Data',
     'network.print': 'Print',
     'network.help': 'Help',
     'network.tutorial': 'Tutorial',
     'network.shortcuts': 'Shortcuts',
     'network.about': 'About',
     
     // Process Parameters
     'process.cycleTime': 'Cycle Time',
     'process.setupTime': 'Setup Time',
     'process.equipmentCount': 'Equipment Count',
     'process.operatorCount': 'Operator Count',
     'process.inputBufferCapacity': 'Input Buffer Capacity',
     'process.outputBufferCapacity': 'Output Buffer Capacity',
     'process.defectRate': 'Defect Rate',
     'process.reworkRate': 'Rework Rate',
     'process.operatingCost': 'Operating Cost',
     'process.machining': 'Machining',
     'process.assembly': 'Assembly',
     'process.inspection': 'Inspection',
     'process.packaging': 'Packaging',
     'process.storage': 'Storage',
     'process.transport': 'Transport',
     'process.basicSettings': 'Basic Settings',
     'process.advancedSettings': 'Advanced Settings',
     'process.materialSettings': 'Material Settings',
     'process.outputSettings': 'Output Settings',
     'process.qualitySettings': 'Quality Settings',
     'process.costSettings': 'Cost Settings',
     'process.scheduleSettings': 'Schedule Settings',
     'process.unit.seconds': 'seconds',
     'process.unit.minutes': 'minutes',
     'process.unit.hours': 'hours',
     'process.unit.pieces': 'pieces',
     'process.unit.percent': '%',
     'process.unit.yen': 'yen',
     
     // Store Settings
     'store.title': 'Store Settings',
     'store.finishedProductStore': 'Finished Product Store',
     'store.componentStore': 'Component Store',
     'store.storeType': 'Store Type',
     'store.inputBufferCapacity': 'Input Buffer Capacity',
     'store.outputBufferCapacity': 'Output Buffer Capacity',
     'store.productionSchedule': 'Production Schedule',
     'store.inventoryLevels': 'Inventory Levels',
     'store.addSchedule': 'Add Schedule',
     'store.addInventory': 'Add Inventory',
     'store.sequence': 'Sequence',
     'store.productName': 'Product Name',
     'store.quantity': 'Quantity',
     'store.unit': 'Unit',
     'store.priority': 'Priority',
     'store.startTime': 'Start Time',
     'store.endTime': 'End Time',
     'store.status': 'Status',
     'store.actions': 'Actions',
     'store.active': 'Active',
     'store.inactive': 'Inactive',
     'store.currentStock': 'Current Stock',
     'store.minStock': 'Min Stock',
     'store.maxStock': 'Max Stock',
     'store.reorderPoint': 'Reorder Point',
     'store.addScheduleTitle': 'Add Production Schedule',
     'store.editScheduleTitle': 'Edit Production Schedule',
     'store.addInventoryTitle': 'Add Inventory Level',
     'store.editInventoryTitle': 'Edit Inventory Level',
     'store.productId': 'Product ID',
     'store.unit.pieces': 'pieces',
     'store.unit.hours': 'hours',
   },
  
  id: {
    // Umum
    'common.save': 'Simpan',
    'common.cancel': 'Batal',
    'common.reset': 'Reset',
    'common.close': 'Tutup',
    'common.confirm': 'Konfirmasi',
    'common.delete': 'Hapus',
    'common.edit': 'Edit',
    'common.add': 'Tambah',
    'common.search': 'Cari',
    'common.loading': 'Memuat...',
    'common.error': 'Error',
    'common.success': 'Berhasil',
    
    // Sidebar
    'sidebar.projects': 'Proyek',
    'sidebar.simulator': 'Simulator',
    'sidebar.networkEditor': 'Editor Jaringan',
    'sidebar.componentEditor': 'Editor Komponen',
    'sidebar.analytics': 'Analitik',
    'sidebar.help': 'Bantuan',
    'sidebar.settings': 'Pengaturan',
    'sidebar.sidebarConfig': 'Konfigurasi Sidebar',
    
    // Panel Pengaturan
    'settings.title': 'Pengaturan',
    'settings.appearance': 'Tampilan',
    'settings.language': 'Bahasa & Wilayah',
    'settings.notifications': 'Notifikasi',
    'settings.dataStorage': 'Data & Penyimpanan',
    'settings.security': 'Keamanan',
    'settings.theme': 'Tema',
    'settings.theme.light': 'Terang',
    'settings.theme.dark': 'Gelap',
    'settings.theme.auto': 'Otomatis',
    'settings.autoSave': 'Aktifkan Auto Save',
    'settings.language.label': 'Bahasa',
    'settings.notifications.enable': 'Aktifkan Notifikasi',
    'settings.simulationSpeed': 'Kecepatan Simulasi',
    'settings.maxIterations': 'Maksimal Iterasi',
    'settings.dataRetention': 'Retensi Data (hari)',
    'settings.securityLevel': 'Tingkat Keamanan',
    'settings.securityLevel.low': 'Rendah',
    'settings.securityLevel.medium': 'Sedang',
    'settings.securityLevel.high': 'Tinggi',
    'settings.securityLevel.info': 'Perubahan tingkat keamanan akan berlaku pada login berikutnya.',
    
    // Konfigurasi Sidebar
    'sidebarConfig.title': 'Konfigurasi Sidebar',
    'sidebarConfig.appearance': 'Tampilan',
    'sidebarConfig.behavior': 'Perilaku',
    'sidebarConfig.shortcuts': 'Pintasan',
    'sidebarConfig.showSidebar': 'Tampilkan Sidebar',
    'sidebarConfig.sidebarWidth': 'Lebar Sidebar',
    'sidebarConfig.currentWidth': 'Saat ini: {width}px',
    'sidebarConfig.hoverHighlight': 'Sorot saat Hover',
    'sidebarConfig.activeItemHighlight': 'Sorot Item Aktif',
    'sidebarConfig.animationEffects': 'Efek Animasi',
    'sidebarConfig.keyboardShortcuts': 'Pintasan Keyboard',
    'sidebarConfig.quickActions': 'Aksi Cepat',
    'sidebarConfig.resetSettings': 'Reset Pengaturan',
    'sidebarConfig.exportSettings': 'Ekspor Pengaturan',
    'sidebarConfig.importSettings': 'Impor Pengaturan',
    
    // Pintasan Keyboard
    'shortcuts.sidebarToggle': 'Ctrl + B: Toggle Sidebar',
    'shortcuts.settingsPanel': 'Ctrl + Shift + S: Panel Pengaturan',
    'shortcuts.sidebarConfig': 'Ctrl + Shift + C: Konfigurasi Sidebar',
    'shortcuts.newProject': 'Ctrl + Shift + N: Proyek Baru',
    
         // Aplikasi
     'app.title': 'Simulator Jalur Produksi Campuran Diskrit',
     'app.productionSimulator': 'Simulator Produksi',
     
     // Editor Jaringan
     'network.title': 'Editor Jaringan',
     'network.addProcess': 'Tambah Proses',
     'network.addStore': 'Tambah Toko',
     'network.addConnection': 'Tambah Koneksi',
     'network.editProcess': 'Edit Proses',
     'network.editStore': 'Edit Toko',
     'network.editConnection': 'Edit Koneksi',
     'network.deleteProcess': 'Hapus Proses',
     'network.deleteStore': 'Hapus Toko',
     'network.deleteConnection': 'Hapus Koneksi',
     'network.processName': 'Nama Proses',
     'network.storeName': 'Nama Toko',
     'network.connectionName': 'Nama Koneksi',
     'network.processType': 'Tipe Proses',
     'network.storeType': 'Tipe Toko',
     'network.connectionType': 'Tipe Koneksi',
     'network.capacity': 'Kapasitas',
     'network.initialStock': 'Stok Awal',
     'network.processingTime': 'Waktu Pemrosesan',
     'network.transportTime': 'Waktu Transport',
     'network.distance': 'Jarak',
     'network.coordinates': 'Koordinat',
     'network.x': 'Koordinat X',
     'network.y': 'Koordinat Y',
     'network.validation': 'Validasi',
     'network.validationSuccess': 'Validasi Berhasil',
     'network.validationError': 'Error Validasi',
     'network.validationWarning': 'Peringatan Validasi',
     'network.saveNetwork': 'Simpan Jaringan',
     'network.loadNetwork': 'Muat Jaringan',
     'network.exportNetwork': 'Ekspor Jaringan',
     'network.importNetwork': 'Impor Jaringan',
     'network.clearNetwork': 'Bersihkan Jaringan',
     'network.undo': 'Undo',
     'network.redo': 'Redo',
     'network.zoomIn': 'Zoom In',
     'network.zoomOut': 'Zoom Out',
     'network.fitToScreen': 'Sesuaikan Layar',
     'network.resetView': 'Reset Tampilan',
     'network.grid': 'Grid',
     'network.snapToGrid': 'Snap ke Grid',
     'network.showLabels': 'Tampilkan Label',
     'network.showConnections': 'Tampilkan Koneksi',
     'network.showProcesses': 'Tampilkan Proses',
     'network.showStores': 'Tampilkan Toko',
     'network.autoLayout': 'Layout Otomatis',
     'network.manualLayout': 'Layout Manual',
     'network.analysis': 'Analisis',
     'network.bottleneckAnalysis': 'Analisis Bottleneck',
     'network.flowAnalysis': 'Analisis Aliran',
     'network.efficiencyAnalysis': 'Analisis Efisiensi',
     'network.costAnalysis': 'Analisis Biaya',
     'network.performanceMetrics': 'Metrik Kinerja',
     'network.throughput': 'Throughput',
     'network.utilization': 'Utilisasi',
     'network.cycleTime': 'Waktu Siklus',
     'network.leadTime': 'Waktu Pimpinan',
     'network.workInProgress': 'Pekerjaan dalam Proses',
     'network.finishedGoods': 'Barang Jadi',
     'network.rawMaterials': 'Bahan Baku',
     'network.workInProgressStore': 'Toko WIP',
     'network.finishedGoodsStore': 'Toko Barang Jadi',
     'network.rawMaterialsStore': 'Toko Bahan Baku',
     'network.machine': 'Mesin',
     'network.worker': 'Pekerja',
     'network.transport': 'Transport',
     'network.buffer': 'Buffer',
     'network.quality': 'Kualitas',
     'network.maintenance': 'Pemeliharaan',
     'network.setup': 'Setup',
     'network.breakdown': 'Kerusakan',
     'network.repair': 'Perbaikan',
     'network.schedule': 'Jadwal',
     'network.shift': 'Shift',
     'network.overtime': 'Lembur',
     'network.break': 'Istirahat',
     'network.availability': 'Ketersediaan',
     'network.efficiency': 'Efisiensi',
     'network.reliability': 'Keandalan',
     'network.flexibility': 'Fleksibilitas',
     'network.scalability': 'Skalabilitas',
     'network.optimization': 'Optimasi',
     'network.simulation': 'Simulasi',
     'network.parameters': 'Parameter',
     'network.results': 'Hasil',
     'network.reports': 'Laporan',
     'network.charts': 'Bagan',
     'network.graphs': 'Grafik',
     'network.tables': 'Tabel',
     'network.exportData': 'Ekspor Data',
     'network.print': 'Cetak',
     'network.help': 'Bantuan',
     'network.tutorial': 'Tutorial',
     'network.shortcuts': 'Pintasan',
     'network.about': 'Tentang',
     
     // Parameter Proses
     'process.cycleTime': 'Waktu Siklus',
     'process.setupTime': 'Waktu Setup',
     'process.equipmentCount': 'Jumlah Peralatan',
     'process.operatorCount': 'Jumlah Operator',
     'process.inputBufferCapacity': 'Kapasitas Buffer Input',
     'process.outputBufferCapacity': 'Kapasitas Buffer Output',
     'process.defectRate': 'Tingkat Cacat',
     'process.reworkRate': 'Tingkat Perbaikan',
     'process.operatingCost': 'Biaya Operasi',
     'process.machining': 'Pemesinan',
     'process.assembly': 'Perakitan',
     'process.inspection': 'Inspeksi',
     'process.packaging': 'Pengemasan',
     'process.storage': 'Penyimpanan',
     'process.transport': 'Transport',
     'process.basicSettings': 'Pengaturan Dasar',
     'process.advancedSettings': 'Pengaturan Lanjutan',
     'process.materialSettings': 'Pengaturan Material',
     'process.outputSettings': 'Pengaturan Output',
     'process.qualitySettings': 'Pengaturan Kualitas',
     'process.costSettings': 'Pengaturan Biaya',
     'process.scheduleSettings': 'Pengaturan Jadwal',
     'process.unit.seconds': 'detik',
     'process.unit.minutes': 'menit',
     'process.unit.hours': 'jam',
     'process.unit.pieces': 'buah',
     'process.unit.percent': '%',
     'process.unit.yen': 'yen',
   },
  
  zh: {
    // 通用
    'common.save': '保存',
    'common.cancel': '取消',
    'common.reset': '重置',
    'common.close': '关闭',
    'common.confirm': '确认',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.add': '添加',
    'common.search': '搜索',
    'common.loading': '加载中...',
    'common.error': '错误',
    'common.success': '成功',
    
    // 侧边栏
    'sidebar.projects': '项目',
    'sidebar.simulator': '模拟器',
    'sidebar.networkEditor': '网络编辑器',
    'sidebar.componentEditor': '组件编辑器',
    'sidebar.analytics': '分析',
    'sidebar.help': '帮助',
    'sidebar.settings': '设置',
    'sidebar.sidebarConfig': '侧边栏配置',
    
    // 设置面板
    'settings.title': '设置',
    'settings.appearance': '外观',
    'settings.language': '语言和地区',
    'settings.notifications': '通知',
    'settings.dataStorage': '数据和存储',
    'settings.security': '安全',
    'settings.theme': '主题',
    'settings.theme.light': '浅色',
    'settings.theme.dark': '深色',
    'settings.theme.auto': '自动',
    'settings.autoSave': '启用自动保存',
    'settings.language.label': '语言',
    'settings.notifications.enable': '启用通知',
    'settings.simulationSpeed': '模拟速度',
    'settings.maxIterations': '最大迭代次数',
    'settings.dataRetention': '数据保留期（天）',
    'settings.securityLevel': '安全级别',
    'settings.securityLevel.low': '低',
    'settings.securityLevel.medium': '中',
    'settings.securityLevel.high': '高',
    'settings.securityLevel.info': '安全级别更改将在下次登录时生效。',
    
    // 侧边栏配置
    'sidebarConfig.title': '侧边栏配置',
    'sidebarConfig.appearance': '外观',
    'sidebarConfig.behavior': '行为',
    'sidebarConfig.shortcuts': '快捷键',
    'sidebarConfig.showSidebar': '显示侧边栏',
    'sidebarConfig.sidebarWidth': '侧边栏宽度',
    'sidebarConfig.currentWidth': '当前: {width}px',
    'sidebarConfig.hoverHighlight': '悬停时高亮',
    'sidebarConfig.activeItemHighlight': '高亮活动项目',
    'sidebarConfig.animationEffects': '动画效果',
    'sidebarConfig.keyboardShortcuts': '键盘快捷键',
    'sidebarConfig.quickActions': '快速操作',
    'sidebarConfig.resetSettings': '重置设置',
    'sidebarConfig.exportSettings': '导出设置',
    'sidebarConfig.importSettings': '导入设置',
    
    // 键盘快捷键
    'shortcuts.sidebarToggle': 'Ctrl + B: 切换侧边栏',
    'shortcuts.settingsPanel': 'Ctrl + Shift + S: 设置面板',
    'shortcuts.sidebarConfig': 'Ctrl + Shift + C: 侧边栏配置',
    'shortcuts.newProject': 'Ctrl + Shift + N: 新项目',
    
         // 应用程序
     'app.title': '混流生产线离散模拟器',
     'app.productionSimulator': '生产模拟器',
     
     // 网络编辑器
     'network.title': '网络编辑器',
     'network.addProcess': '添加流程',
     'network.addStore': '添加存储',
     'network.addConnection': '添加连接',
     'network.editProcess': '编辑流程',
     'network.editStore': '编辑存储',
     'network.editConnection': '编辑连接',
     'network.deleteProcess': '删除流程',
     'network.deleteStore': '删除存储',
     'network.deleteConnection': '删除连接',
     'network.processName': '流程名称',
     'network.storeName': '存储名称',
     'network.connectionName': '连接名称',
     'network.processType': '流程类型',
     'network.storeType': '存储类型',
     'network.connectionType': '连接类型',
     'network.capacity': '容量',
     'network.initialStock': '初始库存',
     'network.processingTime': '处理时间',
     'network.transportTime': '运输时间',
     'network.distance': '距离',
     'network.coordinates': '坐标',
     'network.x': 'X坐标',
     'network.y': 'Y坐标',
     'network.validation': '验证',
     'network.validationSuccess': '验证成功',
     'network.validationError': '验证错误',
     'network.validationWarning': '验证警告',
     'network.saveNetwork': '保存网络',
     'network.loadNetwork': '加载网络',
     'network.exportNetwork': '导出网络',
     'network.importNetwork': '导入网络',
     'network.clearNetwork': '清空网络',
     'network.undo': '撤销',
     'network.redo': '重做',
     'network.zoomIn': '放大',
     'network.zoomOut': '缩小',
     'network.fitToScreen': '适应屏幕',
     'network.resetView': '重置视图',
     'network.grid': '网格',
     'network.snapToGrid': '对齐网格',
     'network.showLabels': '显示标签',
     'network.showConnections': '显示连接',
     'network.showProcesses': '显示流程',
     'network.showStores': '显示存储',
     'network.autoLayout': '自动布局',
     'network.manualLayout': '手动布局',
     'network.analysis': '分析',
     'network.bottleneckAnalysis': '瓶颈分析',
     'network.flowAnalysis': '流程分析',
     'network.efficiencyAnalysis': '效率分析',
     'network.costAnalysis': '成本分析',
     'network.performanceMetrics': '性能指标',
     'network.throughput': '吞吐量',
     'network.utilization': '利用率',
     'network.cycleTime': '周期时间',
     'network.leadTime': '前置时间',
     'network.workInProgress': '在制品',
     'network.finishedGoods': '成品',
     'network.rawMaterials': '原材料',
     'network.workInProgressStore': '在制品存储',
     'network.finishedGoodsStore': '成品存储',
     'network.rawMaterialsStore': '原材料存储',
     'network.machine': '机器',
     'network.worker': '工人',
     'network.transport': '运输',
     'network.buffer': '缓冲',
     'network.quality': '质量',
     'network.maintenance': '维护',
     'network.setup': '设置',
     'network.breakdown': '故障',
     'network.repair': '修理',
     'network.schedule': '计划',
     'network.shift': '班次',
     'network.overtime': '加班',
     'network.break': '休息',
     'network.availability': '可用性',
     'network.efficiency': '效率',
     'network.reliability': '可靠性',
     'network.flexibility': '灵活性',
     'network.scalability': '可扩展性',
     'network.optimization': '优化',
     'network.simulation': '模拟',
     'network.parameters': '参数',
     'network.results': '结果',
     'network.reports': '报告',
     'network.charts': '图表',
     'network.graphs': '图形',
     'network.tables': '表格',
     'network.exportData': '导出数据',
     'network.print': '打印',
     'network.help': '帮助',
     'network.tutorial': '教程',
     'network.shortcuts': '快捷键',
     'network.about': '关于',
     
     // 流程参数
     'process.cycleTime': '周期时间',
     'process.setupTime': '设置时间',
     'process.equipmentCount': '设备数量',
     'process.operatorCount': '操作员数量',
     'process.inputBufferCapacity': '输入缓冲容量',
     'process.outputBufferCapacity': '输出缓冲容量',
     'process.defectRate': '缺陷率',
     'process.reworkRate': '返工率',
     'process.operatingCost': '运营成本',
     'process.machining': '机械加工',
     'process.assembly': '装配',
     'process.inspection': '检验',
     'process.packaging': '包装',
     'process.storage': '存储',
     'process.transport': '运输',
     'process.basicSettings': '基本设置',
     'process.advancedSettings': '高级设置',
     'process.materialSettings': '材料设置',
     'process.outputSettings': '输出设置',
     'process.qualitySettings': '质量设置',
     'process.costSettings': '成本设置',
     'process.scheduleSettings': '计划设置',
     'process.unit.seconds': '秒',
     'process.unit.minutes': '分钟',
     'process.unit.hours': '小时',
     'process.unit.pieces': '件',
     'process.unit.percent': '%',
     'process.unit.yen': '日元',
   },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'ja';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
    document.documentElement.lang = lang;
  };

  const t = (key: string): string => {
    const translation = translations[language][key];
    if (!translation) {
      console.warn(`Translation missing for key: ${key} in language: ${language}`);
      return key;
    }
    return translation;
  };

  const getCurrentLanguageName = (): string => {
    return languages[language].nativeName;
  };

  const getAvailableLanguages = () => {
    return Object.entries(languages).map(([code, lang]) => ({
      code: code as Language,
      name: lang.name,
      nativeName: lang.nativeName,
    }));
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const value: LanguageContextType = {
    language,
    setLanguage,
    t,
    getCurrentLanguageName,
    getAvailableLanguages,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}; 